*** Starting uWSGI 2.0.19.1 (64bit) on [Sat May  1 14:35:29 2021] ***
compiled with version: 9.3.0 on 30 April 2021 09:19:35
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: iZ2ze6gybozdadg5rjn1mmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/wx/flask_test/uwsgi
writing pidfile to /root/wx/flask_test/uwsgi/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/wx/flask_test
your processes number limit is 7730
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.24.4.127:5555 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55976b691850
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
unable to find "application" callable in file /root/wx/flask_test/main.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27548)
spawned uWSGI worker 1 (pid: 27549, cores: 1)
*** Stats server enabled on /root/wx/flask_test/uwsgi/uwsgi.status fd: 9 ***
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat May  1 14:35:39 2021] ***
compiled with version: 9.3.0 on 30 April 2021 09:19:35
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: iZ2ze6gybozdadg5rjn1mmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/wx/flask_test/uwsgi
writing pidfile to /root/wx/flask_test/uwsgi/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/wx/flask_test
your processes number limit is 7730
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (172.24.4.127:5555).
bind(): Address already in use [core/socket.c line 769]
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/wx/flask_test/uwsgi
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (172.24.4.127:5555)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat May  1 14:36:51 2021] ***
compiled with version: 9.3.0 on 30 April 2021 09:19:35
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: iZ2ze6gybozdadg5rjn1mmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/wx/flask_test/uwsgi
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/wx/flask_test
your processes number limit is 7730
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 172.24.4.127:5555 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55d30cae4240
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
unable to find "application" callable in file /root/wx/flask_test/main.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 27548)
spawned uWSGI worker 1 (pid: 27600, cores: 1)
*** Stats server enabled on /root/wx/flask_test/uwsgi/uwsgi.status fd: 9 ***
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat May  1 14:37:15 2021] ***
compiled with version: 9.3.0 on 30 April 2021 09:19:35
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: iZ2ze6gybozdadg5rjn1mmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/wx/flask_test/uwsgi
writing pidfile to /root/wx/flask_test/uwsgi/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/wx/flask_test
your processes number limit is 7730
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (172.24.4.127:5555).
bind(): Address already in use [core/socket.c line 769]
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/wx/flask_test/uwsgi
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (172.24.4.127:5555)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat May  1 14:39:29 2021] ***
compiled with version: 9.3.0 on 30 April 2021 09:19:35
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: iZ2ze6gybozdadg5rjn1mmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/wx/flask_test/uwsgi
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/wx/flask_test
your processes number limit is 7730
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 172.24.4.127:5555 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55b2d55c8240
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
unable to find "application" callable in file /root/wx/flask_test/main.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 27548)
spawned uWSGI worker 1 (pid: 27655, cores: 1)
*** Stats server enabled on /root/wx/flask_test/uwsgi/uwsgi.status fd: 9 ***
Sat May  1 14:39:45 2021 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat May  1 14:40:20 2021] ***
compiled with version: 9.3.0 on 30 April 2021 09:19:35
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: iZ2ze6gybozdadg5rjn1mmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/wx/flask_test/uwsgi
writing pidfile to /root/wx/flask_test/uwsgi/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/wx/flask_test
your processes number limit is 7730
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.24.4.127:5555 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x559f7e31b850
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
unable to find "application" callable in file /root/wx/flask_test/main.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27683)
spawned uWSGI worker 1 (pid: 27684, cores: 1)
*** Stats server enabled on /root/wx/flask_test/uwsgi/uwsgi.status fd: 9 ***
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat May  1 15:08:11 2021] ***
compiled with version: 9.3.0 on 30 April 2021 09:19:35
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: iZ2ze6gybozdadg5rjn1mmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/wx/flask_test/uwsgi
writing pidfile to /root/wx/flask_test/uwsgi/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/wx/flask_test
your processes number limit is 7730
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5555 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
Python main interpreter initialized at 0x5565447386f0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
unable to find "application" callable in file main.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28030)
spawned uWSGI worker 1 (pid: 28031, cores: 1)
*** Stats server enabled on 127.0.0.1:9191 fd: 9 ***
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/1] 81.69.101.193 () {44 vars in 781 bytes} [Sat May  1 15:13:39 2021] POST /wx?signature=e0271a70446f604247b81d25c04429905039d680&timestamp=1619853219&nonce=443898221&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/2] 81.69.101.193 () {44 vars in 780 bytes} [Sat May  1 15:23:38 2021] POST /wx?signature=01df19e51108069e531cb9a065b442f33256bb26&timestamp=1619853817&nonce=825466828&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/3] 81.69.101.193 () {44 vars in 781 bytes} [Sat May  1 15:24:15 2021] POST /wx?signature=dd2b8090bb38b2f99b4ce23cdef712415d57968d&timestamp=1619853855&nonce=641538294&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/4] 81.69.101.193 () {44 vars in 781 bytes} [Sat May  1 15:27:33 2021] POST /wx?signature=f2084441c5293bae4879b181dcba6e8ca96f77f6&timestamp=1619854053&nonce=951344907&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/5] 81.69.101.193 () {44 vars in 782 bytes} [Sat May  1 15:28:14 2021] POST /wx?signature=38af0a4e11b0bef6e83fe7d0893c101deecfb90f&timestamp=1619854094&nonce=1592658974&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/6] 81.69.101.193 () {44 vars in 783 bytes} [Sat May  1 15:28:27 2021] POST /wx?signature=4b105841afa98e9352e2adf43b3087867c6aa2d5&timestamp=1619854107&nonce=1614097001&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/7] 81.69.101.193 () {44 vars in 781 bytes} [Sat May  1 15:29:36 2021] POST /wx?signature=3d66b862982cbbe77b96381d3601a0469c16ae44&timestamp=1619854176&nonce=152983877&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/8] 81.69.101.193 () {44 vars in 783 bytes} [Sat May  1 15:29:58 2021] POST /wx?signature=7ab0774453040d779456649ff3497f07b684e1ab&timestamp=1619854198&nonce=1806536220&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/9] 180.149.125.175 () {40 vars in 572 bytes} [Sat May  1 15:33:53 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/10] 81.69.101.193 () {44 vars in 781 bytes} [Sat May  1 15:46:47 2021] POST /wx?signature=c15696c59856e2a2f4f3c54bf1e6b21c1c074a5c&timestamp=1619855207&nonce=453117758&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/11] 61.151.206.18 () {46 vars in 559 bytes} [Sat May  1 15:47:53 2021] POST / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/12] 61.151.182.104 () {46 vars in 560 bytes} [Sat May  1 15:48:20 2021] POST / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/13] 61.151.207.111 () {46 vars in 560 bytes} [Sat May  1 15:48:21 2021] POST / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/14] 81.69.101.193 () {44 vars in 779 bytes} [Sat May  1 15:53:22 2021] POST /wx?signature=a1a91e804d4fb0212644a1c4abb24ce6ede35355&timestamp=1619855602&nonce=66883501&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/15] 81.69.101.193 () {44 vars in 781 bytes} [Sat May  1 15:53:28 2021] POST /wx?signature=7e458cf625e0282e50233d3d614c8ccae08e58e3&timestamp=1619855608&nonce=997811972&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/16] 81.69.101.193 () {44 vars in 783 bytes} [Sat May  1 15:54:47 2021] POST /wx?signature=1c41c65ab9f2250b6c86786ce15e0473e1f8970e&timestamp=1619855687&nonce=2118044597&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 28031|app: -1|req: -1/17] 81.69.101.193 () {44 vars in 781 bytes} [Sat May  1 15:54:53 2021] POST /wx?signature=9cf40514682297d5db2865745b4f157144d4afdf&timestamp=1619855693&nonce=880281380&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat May  1 15:56:40 2021] ***
compiled with version: 9.3.0 on 30 April 2021 09:19:35
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: iZ2ze6gybozdadg5rjn1mmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/wx/flask_test/uwsgi
writing pidfile to /root/wx/flask_test/uwsgi/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/wx/flask_test
your processes number limit is 7730
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5555).
bind(): Address already in use [core/socket.c line 769]
Sat May  1 15:57:52 2021 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat May  1 15:58:08 2021 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat May  1 16:00:09 2021] ***
compiled with version: 9.3.0 on 30 April 2021 09:19:35
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: iZ2ze6gybozdadg5rjn1mmZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/wx/flask_test/uwsgi
writing pidfile to /root/wx/flask_test/uwsgi/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/wx/flask_test
your processes number limit is 7730
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5555 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
Python main interpreter initialized at 0x555ebfc46890
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
unable to find "application" callable in file core.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30993)
spawned uWSGI worker 1 (pid: 30995, cores: 1)
*** Stats server enabled on 127.0.0.1:9191 fd: 9 ***
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 30995|app: -1|req: -1/1] 81.69.101.193 () {44 vars in 783 bytes} [Sat May  1 16:01:47 2021] POST /wx?signature=69db2f1b0e5efd1b18c219668d1cb413ffdffa62&timestamp=1619856107&nonce=1843289498&openid=oUPiFw9AH4KZACXX3uZIAxri9Css => generated 21 bytes in 3 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
